version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zaplink-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://zaplink:zaplink_secret_pw@postgres:5432/zaplink?schema=public
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_SECRET=zaplink_super_secure_production_secret_32bytes
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - IP_SALT=zaplink_production_ip_salt
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: zaplink-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=zaplink
      - POSTGRES_PASSWORD=zaplink_secret_pw
      - POSTGRES_DB=zaplink
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zaplink -d zaplink"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: zaplink-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
